name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        # https://github.com/peaceiris/actions-label-commenter#work-with-other-auto-label-actions
        with:
          repo-token: "${{ secrets.GH_PAT }}"
