name: Pull Request Reminder

on:
  pull_request_target:
    types:
      - labeled

jobs:
  reminder:
    if: ${{ github.event.label.name == 'Configurations' }}
    runs-on: ubuntu-latest

    steps:
    - name: Comment PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          This pull request contains changes to the configuration file. Please make sure the documentation in [NexT website](https://theme-next.js.org/docs/) is changed or added.
          Please edit relevant source files here: https://github.com/next-theme/theme-next-docs/tree/master/source/docs and create a pull request with the changes here: https://github.com/next-theme/theme-next-docs/pulls
